#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : R-litedown
Version  : 0.7
Release  : 2
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/litedown_0.7.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/litedown_0.7.tar.gz
Summary  : A Lightweight Version of R Markdown
Group    : Development/Tools
License  : MIT
Requires: R-commonmark
Requires: R-xfun
BuildRequires : R-commonmark
BuildRequires : R-xfun
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
to lightweight HTML or 'LaTeX' documents with the 'commonmark' package (instead
    of 'Pandoc'). Some missing Markdown features in 'commonmark' are also
    supported, such as raw HTML or 'LaTeX' blocks, 'LaTeX' math, superscripts,
    subscripts, footnotes, element attributes, and appendices,
    but not all 'Pandoc' Markdown features are (or will be) supported. With
    additional JavaScript and CSS, you can also create HTML slides and articles.
    This package can be viewed as a trimmed-down version of R Markdown and
    'knitr'. It does not aim at rich Markdown features or a large variety of
    output formats (the primary formats are HTML and 'LaTeX'). Book and website
    projects of multiple input documents are also supported.

%prep
%setup -q -n litedown

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744124285

%install
export SOURCE_DATE_EPOCH=1744124285
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/litedown/DESCRIPTION
/usr/lib64/R/library/litedown/INDEX
/usr/lib64/R/library/litedown/LICENSE
/usr/lib64/R/library/litedown/Meta/Rd.rds
/usr/lib64/R/library/litedown/Meta/features.rds
/usr/lib64/R/library/litedown/Meta/hsearch.rds
/usr/lib64/R/library/litedown/Meta/links.rds
/usr/lib64/R/library/litedown/Meta/nsInfo.rds
/usr/lib64/R/library/litedown/Meta/package.rds
/usr/lib64/R/library/litedown/Meta/vignette.rds
/usr/lib64/R/library/litedown/NAMESPACE
/usr/lib64/R/library/litedown/NEWS.md
/usr/lib64/R/library/litedown/R/litedown
/usr/lib64/R/library/litedown/R/litedown.rdb
/usr/lib64/R/library/litedown/R/litedown.rdx
/usr/lib64/R/library/litedown/doc/index.html
/usr/lib64/R/library/litedown/doc/slides.R
/usr/lib64/R/library/litedown/doc/slides.Rmd
/usr/lib64/R/library/litedown/doc/slides.html
/usr/lib64/R/library/litedown/help/AnIndex
/usr/lib64/R/library/litedown/help/aliases.rds
/usr/lib64/R/library/litedown/help/litedown.rdb
/usr/lib64/R/library/litedown/help/litedown.rdx
/usr/lib64/R/library/litedown/help/paths.rds
/usr/lib64/R/library/litedown/html/00Index.html
/usr/lib64/R/library/litedown/html/R.css
/usr/lib64/R/library/litedown/resources/default.css
/usr/lib64/R/library/litedown/resources/listing.css
/usr/lib64/R/library/litedown/resources/litedown.html
/usr/lib64/R/library/litedown/resources/litedown.latex
/usr/lib64/R/library/litedown/resources/server.css
/usr/lib64/R/library/litedown/resources/server.js
/usr/lib64/R/library/litedown/resources/snap.css
/usr/lib64/R/library/litedown/resources/snap.js
/usr/lib64/R/library/litedown/tests/empty.R
/usr/lib64/R/library/litedown/tests/examples.R
/usr/lib64/R/library/litedown/tests/smartypants.R
